# syntax=docker/dockerfile:1.4

FROM python:3.10-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./
COPY gunicorn_config.py gunicorn_config.py

RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r requirements.txt

    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

ENV FLASK_APP microblog.py
ENV prometheus_multiproc_dir /tmp

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]